### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by Mixaer23** [Mixaer23/avito-case#1]
Создаю issue для проверки

**Comment by avito-ds** [comment]
привет! твой результат:

```
Задача 1
	Бытовая электроника: 0.8849367994461794
	Недвижимость: 0.9356335361248485
	Транспорт: 0.9620064152118271
	Работа: 0.8090914877930133
	Для дома и дачи: 0.9051383890458109
	Услуги: 0.8135351760132077
	Личные вещи: 0.8794723063000871
	Для бизнеса: 0.8809840050874609
	Хобби и отдых: 0.8671145858408681
	Животные: 0.8673397442886529
mixaer23 ROC AUC: 0.8805

Задача 2
mixaer23 IOU: 0.08
```

Пока не удалось пробить порог, но можешь попробовать ещё.
Пока что закроем issue, если будут какие-то обновления, то можно переоткрыть этот или создать новый.

**Comment by Mixaer23** [comment]
Привет, спасибо за фидбек!
Есть пара идей, как улучшить, постараюсь прислать как можно скорее)
--
С уважением,
Михаил четверг, 27 января 2022г., 12:54 +03:00 от avito-ds  ***@***.*** :
